// actionTypes.js

// Movies/TV Shows
export const FETCH_POPULAR_MOVIES_REQUEST = "FETCH_POPULAR_MOVIES_REQUEST";
export const FETCH_POPULAR_MOVIES_SUCCESS = "FETCH_POPULAR_MOVIES_SUCCESS";
export const FETCH_POPULAR_MOVIES_FAILURE = "FETCH_POPULAR_MOVIES_FAILURE";

export const FETCH_TOP_RATED_MOVIES_REQUEST = "FETCH_TOP_RATED_MOVIES_REQUEST";
export const FETCH_TOP_RATED_MOVIES_SUCCESS = "FETCH_TOP_RATED_MOVIES_SUCCESS";
export const FETCH_TOP_RATED_MOVIES_FAILURE = "FETCH_TOP_RATED_MOVIES_FAILURE";

export const FETCH_TRENDING_REQUEST = "FETCH_TRENDING_MOVIES_REQUEST";
export const FETCH_TRENDING_SUCCESS = "FETCH_TRENDING_MOVIES_SUCCESS";
export const FETCH_TRENDING_FAILURE = "FETCH_TRENDING_MOVIES_FAILURE";