export const FETCH_ALL_WEBSERIES_REQUEST = 'FETCH_ALL_WEBSERIES_REQUEST';
export const FETCH_ALL_WEBSERIES_SUCCESS = 'FETCH_ALL_WEBSERIES_SUCCESS';
export const FETCH_ALL_WEBSERIES_FAILURE = 'FETCH_ALL_WEBSERIES_FAILURE';

export const FETCH_WEBSERIES_BY_ID_SUCCESS = 'FETCH_WEBSERIES_BY_ID_SUCCESS';
export const FETCH_WEBSERIES_BY_GENRE_SUCCESS = 'FETCH_WEBSERIES_BY_GENRE_SUCCESS';

export const CREATE_WEBSERIES_SUCCESS = 'CREATE_WEBSERIES_SUCCESS';

export const DELETE_WEBSERIES_SUCCESS = 'DELETE_WEBSERIES_SUCCESS';